# -*- coding: utf-8 -*-
"""Rohit Madan Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wtVwz0LS1qQ7lJVeyHy8H_vg_X08-s7V
"""

import requests
from bs4 import BeautifulSoup 
import datetime


date_entry = input('Enter From date in YYYY-MM-DD format : ')
year, month, day = map(int, date_entry.split('-'))
date1 = datetime.date(year, month, day)

date_entry = input('Enter To date in YYYY-MM-DD format : ')
year, month, day = map(int, date_entry.split('-'))
date2 = datetime.date(year, month, day)


URL="http://www.imdb.com/search/title?release_date=" + str(date1) + "," + str(date2) 

r = requests.get(URL) 
  
soup = BeautifulSoup(r.content, 'html5lib') 
  
movies=[]  # a list to store movies
  
table = soup.find('div', attrs = {'class':'lister-list'}) 

for row2 in table.findAll('h3', attrs = {'class':'lister-item-header'}):
  print(row2.span.text,row2.a.text)